import 'package:flutter/material.dart';

class GlobalVariables {
  static const Color backgroundColor = Color(0xff1c1c27);
  static const Color cardBackgroundColor = Color(0xff28293d);
  static const Color primaryColor = Color(0xff3d7bfa);

  static const List<String> provinceList = [
    "Pradesh no.1",
    "Madhesh Pradesh",
    "Bagmati Pradesh",
    "Gandaki Pradesh",
    "Lumbini Pradesh",
    "Karnali Pradesh",
    "Sudur Pashchim Pradesh",
  ];

  static const List<String> districtList = [
    "Bhojpur",
    "Dhankuta",
    "Ilam",
    "Jhapa",
    "Khotang",
    "Morang",
    "Okhaldhunga",
    "Panchthar",
    "Sankhuwasabha",
    "Solukhumbu",
    "Sunsari",
    "Taplejung",
    "Terhathum",
    "Udayapur",
    "Saptari",
    "Siraha",
    "Dhanusa",
    "Mahottari",
    "Sarlahi",
    "Bara",
    "Parsa",
    "Rautahat",
    "Sindhuli",
    "Ramechhap",
    "Dolakha",
    "Bhaktapur",
    "Dhading",
    "Kathmandu",
    "Kavrepalanchok",
    "Lalitpur",
    "Nuwakot",
    "Rasuwa",
    "Sindhupalchok",
    "Chitwan",
    "Makwanpur",
    "Baglung",
    "Gorkha",
    "Kaski",
    "Lamjung",
    "Manang",
    "Mustang",
    "Myagdi",
    "Nawalpur",
    "Parbat",
    "Syangja",
    "Tanahun",
    "Kapilvastu",
    "Parasi",
    "Rupandehi",
    "Arghakhanchi",
    "Gulmi",
    "Palpa",
    "Dang",
    "Pyuthan",
    "Rolpa",
    "Eastern",
    "Banke",
    "Bardiya",
    "Western",
    "Salyan",
    "Dolpa",
    "Humla",
    "Jumla",
    "Kalikot",
    "Mugu",
    "Surkhet",
    "Dailekh",
    "Jajarkot",
    "Kailali",
    "Achham",
    "Doti",
    "Bajhang",
    "Bajura",
    "Kanchanpur",
    "Dadeldhura",
    "Baitadi",
    "Darchula"
  ];
}
